- services/resources-getter.js
> Search - User wants to search on a reference "displayField"

- CHANGELOG.md
- services/line-stat-getter.js
- services/pie-stat-getter.js
- services/resources-getter.js
- services/value-stat-getter.js
(restricted to simple conditions).
> Filters - Users want the OR filter operator with their conditions

- CHANGELOG.md
- services/line-stat-getter.js
- services/pie-stat-getter.js
- services/value-stat-getter.js
> Chart Filters - Support chart filters on belongsTo associations

- CHANGELOG.md
- services/pie-stat-getter.js
> Pie Charts - Support group by on belongsTo associations

- CHANGELOG.md
- index.js
- package.json
See [Issue #30](https://github.com/ForestAdmin/forest-express/issues/30) in [forest-express](https://github.com/ForestAdmin/forest-express)
> Expose Deserialization and Schemas Interfaces to the API

- CHANGELOG.md
- adapters/sequelize.js
- services/pie-stat-getter.js
This PR comes with this one: https://github.com/ForestAdmin/forest-express/pull/67
> [+] Types Support - Support Dateonly field type

- CHANGELOG.md
- package.json
⚠️ Wait for this PR https://github.com/ForestAdmin/forest-express/pull/70 merge before approval ⚠️
> [+] Setup Guide - Add integration field to the collections to distinguish Smart Collections and Collections from integrations

- CHANGELOG.md
- package.json
⚠️ Wait for the following PR https://github.com/ForestAdmin/forest-express/pull/73 to merge ⚠️
> [+] Smart Fields - Developers can now define Smart Fields setters

- CHANGELOG.md
- package.json
Wait for this PR to be merged: https://github.com/ForestAdmin/forest-express/pull/83
> [*] HasMany Smart Fields - Fix routes conflicts between hasMany Smart Fields and other associations

- CHANGELOG.md
- docker-compose.yml
- package.json
- services/line-stat-getter.js
- services/pie-stat-getter.js
- test/index.js
- utils/database.js
- utils/schema.js
> [*] Pie Charts - Support MSSQL dialect for "Manual" Pie charts

- CHANGELOG.md
- index.js
> [+] Technical - Send sequelize version and database type in apimap.

- CHANGELOG.md
- services/has-many-getter.js
- services/query-builder.js
- services/resources-getter.js
- test/index.js
> [*] Resources Getter - Support MSSQL records list retrieval without order in the query

- CHANGELOG.md
- services/resource-finder.js
- services/resource-getter.js
- services/resource-remover.js
- services/resource-updater.js
- test/index.js
> [-] Record Deletions - Handle the record deletion on models having a composite primary key

- CHANGELOG.md
- index.js
> [*] Liana Version - Prevent server crash on bad format version.

- CHANGELOG.md
- services/operator-date-interval-parser.js
- test/index.js
> [+] Filters - Add the before x hours operator.

- CHANGELOG.md
- package-lock.json
- services/line-stat-getter.js
- services/pie-stat-getter.js
> [-] Technical - Support Sequelize 4.2.0

- CHANGELOG.md
- adapters/sequelize.js
> [*] Apimaps - Prevent foreign key field creation for belongsTo associations having a constaints set to false

- .eslintrc.js
- .travis.yml
- CHANGELOG.md
- README.md
- package.json
- services/handle-search.js
- services/has-many-getter.js
- services/operator-value-parser.js
- services/pie-stat-getter.js
- services/query-builder.js
- services/resource-updater.js
- services/resources-getter.js
- services/search-builder.js
- test/fixtures/db.json
- test/index.js
> [+] Search - Users can search on the hasMany associated data of a specific record

- CHANGELOG.md
- services/operator-value-parser.js
- test/index.js
> [*] Filters - Boolean filter condition with a null value will not crash anymore

- CHANGELOG.md
- package.json
- services/query-builder.js
> [*] Sorting - Fix the sorting issue on the primary keys for MSSQL project

- CHANGELOG.md
- services/search-builder.js
> [-] Search - Split "simple" and "deep" search features with a new param

- CHANGELOG.md
- index.js
- package.json
- services/records-exporter.js
> [+] Exports - Forest can now handle large data exports

- CHANGELOG.md
- adapters/sequelize.js
Fix https://github.com/ForestAdmin/forest-express-sequelize/issues/121
> [*] Record Creations - Prevent issue on record creations for models with UUID primary key default value

- CHANGELOG.md
- package.json
> [*] Exports - Fix bad initial implementation for exports authentication

- CHANGELOG.md
- adapters/sequelize.js
> [*] Apimap - Fix collections schema for collections having snakecase foreign keys

- CHANGELOG.md
- index.js
> Allow users to call a ResourcesRoute from their app.

- CHANGELOG.md
- index.js
> [+] Integrations - Add the Layer integration

- CHANGELOG.md
- adapters/sequelize.js
- services/has-many-getter.js
- services/records-exporter.js
> [*] HasMany Display - Fix HasMany association display for models having a composite primary key

- CHANGELOG.md
- services/query-builder.js
- services/search-builder.js
- test/index.js
- utils/database.js
> [*] Search - Fix a potential search regression due to multi database support (1.3.0)

- CHANGELOG.md
- services/composite-keys-manager.js
> [*] Composite Primary Keys - Forest handle null values.

- CHANGELOG.md
- services/pie-stat-getter.js
> [*] Pie Charts - Prevent a potential crash on models having a column named "key"

- CHANGELOG.md
- services/base-stat-getter.js
- services/line-stat-getter.js
- services/pie-stat-getter.js
- services/value-stat-getter.js
> [*] Charts - Fix broken charts if they contain relationship filters on model fields that have a different column name

- CHANGELOG.md
- services/line-stat-getter.js
- utils/database.js
> Support SQLite for line stat SQL queries

- CHANGELOG.md
- index.js
> Fix the init phase when sequelize option is not present

- CHANGELOG.md
- services/line-stat-getter.js
> [*] Line Charts - Fix Line Charts potential crash on Postgresql databases

- CHANGELOG.md
- services/resources-getter.js
- services/search-builder.js
- test/fixtures/db.json
- test/index.js
> [*] Search - Fix the regression of the searchFields option

- CHANGELOG.md
- adapters/sequelize.js
> [+] Types Support - Support Point field type

- .eslintrc.js
- CHANGELOG.md
- services/search-builder.js
- test/fixtures/db.json
- test/index.js
Fix: https://github.com/ForestAdmin/forest-express-sequelize/issues/140
> [*] Search - Fix a regression on UUID fields search

- CHANGELOG.md
- services/errors.js
- services/has-many-dissociator.js
> [*] HasMany Dissociation - Catch SQL constraints errors on record dissociation

- CHANGELOG.md
- services/search-builder.js
> [-] Performance - Improve MSSQL search performances

- CHANGELOG.md
- adapters/sequelize.js
> [*] Validations - Allow an array with one value to define minimum value length validation

- CHANGELOG.md
- package.json
- services/line-stat-getter.js
- services/operator-date-interval-parser.js
- test/index.js
- yarn.lock
> [*] Charts - Fix some bad Line charts aggregation due to Daylight Saving Time

- CHANGELOG.md
- adapters/sequelize.js
- test/index.js
> [-] Apimap - Do not send fields with an unknown type in the Apimap anymore

- CHANGELOG.md
- index.js
- package.json
- services/query-stat-getter.js
```sql
SELECT count(*) as value
FROM users
where id = ?;
```
```sql
SELECT COUNT(*) as value, charts.type as key
from charts
group by type;
```
```sql
select to_char(date_trunc('Month', users."createdAt"), 'YYYY-MM-DD 00:00:00') as key, count(*) as value
from users
GROUP BY 1
ORDER BY 1;
```
> [+] Charts - Users can create charts using raw database queries with the Live Query option

- CHANGELOG.md
- services/base-stat-getter.js
- services/line-stat-getter.js
- services/operator-date-interval-parser.js
- services/operator-value-parser.js
- services/pie-stat-getter.js
- services/resources-getter.js
- services/search-builder.js
- services/value-stat-getter.js
- test/fixtures/db.json
- test/index.js
- utils/operators.js
> [-] Security - Support new Sequelize Operators for a reinforced security

- CHANGELOG.md
- services/query-stat-getter.js
> [*] Live Queries - Prevent the execution of obvious "write" queries

- CHANGELOG.md
- services/operator-date-interval-parser.js
- services/search-builder.js
- test/index.js
> [+] Filters - Add a new "is after X hours ago" operator to filter on date fields

- CHANGELOG.md
- package.json
- yarn.lock
> [-] Security - Fix low impact vulnerabilities

- CHANGELOG.md
- services/query-stat-getter.js
> [*] Live Query - Replace all occurences of the special character '?' in the Live Query mode

- CHANGELOG.md
- package.json
- yarn.lock
> [*] Smart Actions - "Single" type Smart Action forms can now be prefilled with contextual values

- CHANGELOG.md
- package.json
- services/base-stat-getter.js
- services/operator-value-parser.js
- services/pie-stat-getter.js
- yarn.lock
> [*] Security - Upgrade the lodash dependency for security reasons

- CHANGELOG.md
- index.js
- package.json
- services/has-many-getter.js
- services/records-exporter.js
- services/resources-getter.js
- services/search-builder.js
- test/index.js
- utils/records-decorator.js
- yarn.lock
> [+] Search - Display highlighted matches on table view when searching

- CHANGELOG.md
- services/live-query-checker.js
- services/query-stat-getter.js
- services/resources-getter.js
- test/index.js
> Let users define segments using SQL

- CHANGELOG.md
- package.json
> [*] Technical - Cleanup the dependencies

- services/leaderboard-stat-getter.js
> Review rename

- CHANGELOG.md
- adapters/sequelize.js
> [+] Technical - Add a new apimap property "relationship"

- CHANGELOG.md
- services/has-many-getter.js
> [*] Performance - Make the related data count retrieval much more efficient if the result contains thousands of records

- CHANGELOG.md
- adapters/sequelize.js
- index.js
- package.json
- services/leaderboard-stat-getter.js
- yarn.lock
> [+] Charts - Users can create Objective and Leaderboard Charts

- CHANGELOG.md
- index.js
- services/pie-stat-getter.js
- utils/orm.js
> [*] Pie Charts - Fix potential bad "dateonly" values for projects using Sequelize 4+

- CHANGELOG.md
- services/resource-creator.js
> [*] Records Creation - Prevent associations defined while creating a new record from overwriting associations created by hooks

- CHANGELOG.md
- services/belongs-to-updater.js
> [*] Records Update - Allow model hooks to change fields values while updating a belongsTo or hasOne association

- CHANGELOG.md
- index.js
To test, follow the instructions here: https://trello.com/c/DeSWsMad/2641-8-integrations-mixpanel-last-events-on-all-stacks
> [+] Integrations - Mixpanel last events

- CHANGELOG.md
- package.json
- services/has-many-getter.js
- services/resources-getter.js
- test/index.js
- yarn.lock
> [-] Performance - Improve the speed of listing the records by executing their count into another request

- CHANGELOG.md
- services/resource-remover.js
> [-] Records Deletion - Delete a record which has already been deleted does not display an error anymore

- .eslintrc.js
- CHANGELOG.md
- services/has-many-getter.js
- services/query-builder.js
- services/search-builder.js
> [*] List Related Records - Fix count of related records when relation is ManyToMany

- CHANGELOG.md
- services/resources-getter.js
> [*] Smart Segments - Smart segments work if primary key is not named id

- CHANGELOG.md
- services/has-many-getter.js
> [*] Associations - Fix limit and offset of the query getting has many associations

- .eslint-bin/js-list.json
- src/services/resources-getter.js
> [-] Linter - ES-Lint compliance on services/resources-getter.js

- CHANGELOG.md
- src/services/line-stat-getter.js
- src/services/pie-stat-getter.js
- src/services/resources-getter.js
> [-] Linter - Rename opts to options in stat getters

- CHANGELOG.md
- src/services/pie-stat-getter.js
- test/index.js
- [ x] Write an explicit title for the Pull Request
- [ x] Write changes made in the CHANGELOG.md
- [ x] Create automatic tests
- [ x] Test manually the implemented changes
- [ x] Review my own code (indentation, syntax, style, simplicity, readability)
> [*] Pie Chart - Fix capability to have a chart grouped by a reference field with an alias.

- CHANGELOG.md
- src/services/search-builder.js
- src/utils/orm.js
> [*] List Records - Search on table with uuidv1 or v4 does not crash

- CHANGELOG.md
- src/services/filters-parser.js
- src/services/line-stat-getter.js
- src/services/pie-stat-getter.js
- src/services/query-builder.js
- src/services/resources-getter.js
- src/services/value-stat-getter.js
- src/utils/query.js
- test/services/filters-parser.js
- test/utils/query.js
> [*] Filters - Fix filtering on references fields that have an unconventional column name

- CHANGELOG.md
- src/services/query-builder.js
- src/services/resources-getter.js
- src/utils/orm.js
> [*] List Records - Fix filter on belongs to with name different from fieldName

- .npmignore
- CHANGELOG.md
> [*] NPM Publish - Do not send local environment variables on package publish

- CHANGELOG.md
- test/.eslintrc.js
- test/services/apimap-field-builder.js
- test/services/filters-parser.js
> [-] Technical - Update eslint rules

- CHANGELOG.md
- src/services/belongs-to-updater.js
- src/services/composite-keys-manager.js
- src/services/has-many-associator.js
- src/services/live-query-checker.js
- src/services/query-stat-getter.js
- src/services/resource-creator.js
- src/services/resource-getter.js
There is no more error with linter.
I run `yarn lint --fix` then edited manually some files:
- I removed some blank lines at the beginning of files
- I added name to un-named functions
- I renamed an unused obsolete variable from `association` to `assoc` to avoid `no-shadow` error.
> [*] Technical - Apply eslint rules to `src/services`

- CHANGELOG.md
- package.json
- src/services/filters-parser.js
- src/services/resources-getter.js
- test/services/filters-parser.js
- yarn.lock
This is a change that was needed in `forest-express-mongoose` and so it needed to change the `BaseFilterParser` to async. So this PR is too make the work easier for the next developer working on it (As it will be already asynchrone)
> [-] Technical - Filter parser is now asynchronous

- CHANGELOG.md
- package.json
- yarn.lock
See: https://github.com/ForestAdmin/forest-express/commit/b9ab46c73f5468f0a0336c58480e10f688fcbd9c
> [-] Technical - Upgrade to the `forest-express` v5.1.1

- CHANGELOG.md
- package.json
- src/index.js
- yarn.lock
This PR requires: ForestAdmin/forest-express#278
And can be tested with: ForestAdmin/lumber#324
> [+] Routes - Expose the record services and the permission middleware

- CHANGELOG.md
- src/services/line-stat-getter.js
- src/services/pie-stat-getter.js
- src/services/value-stat-getter.js
> [*] Charts - Fix potential broken charts results if they are configured with filters

- CHANGELOG.md
- src/services/query-builder.js
> [*] Has Many Relationships - Fix sorting on hasMany fields in related data

- .travis.yml
- CHANGELOG.md
> [*] Technical - Ensure that all databases are initialized before running tests

- CHANGELOG.md
- src/services/resources-getter.js
> [*] Segment Live Query - Fix issue where an incorrect live query causes the server to crash.

- .babelrc
- .eslintrc.js
- CHANGELOG.md
- package.json
- yarn.lock
> [-] Technical - Upgrade to babel 7 stable

- .travis.yml
- CHANGELOG.md
- docker-compose.yml
- package.json
- test/index.test.js
- yarn.lock
See: https://github.com/ForestAdmin/lumber/pull/393 & https://github.com/sidorares/node-mysql2/blob/master/Changelog.md
> [+] Database Support - Add support for MySQL 8

- CHANGELOG.md
- src/services/query-builder.js
- test/services/query-builder.test.js
I created this PR because `getOrder` behavior was not clear for me at first glance, and it took me some time to understand what cases the function handles and does not handle.
> [+] Technical - Add test and documentation for query-builder sort method

- CHANGELOG.md
- package.json
- yarn.lock
- This PR uses the branch that will be used to release v6.0 beta.
- The changelog contains the two main changes made on `forest-express`. Maybe I should have included more or less.
- When merged, this should trigger a new breaking change version (i.e: v6)
See: https://github.com/ForestAdmin/forestadmin/pull/1559
> [-] Technical - Update `forest-express` to version 7

- CHANGELOG.md
- package.json
Fix broken release: https://github.com/ForestAdmin/forest-express-sequelize/commit/ebe93d26a7a0aa320fe76113ae0a826720bcd43b
> [*] Technical - Fix release 6.0.0

- CHANGELOG.md
- src/adapters/sequelize.js
- src/services/apimap-field-builder.js
- test/services/apimap-field-builder.test.js
Goes with https://github.com/ForestAdmin/lumber/pull/410
Signed-off-by: Guillaume Deslandes <guillaumed@forestadmin.com>
> [*] Technical - Unwrap default values in APIMap field builder

- CHANGELOG.md
- package.json
- yarn.lock
> [-] Dependency - Upgrade the `forest-express` dependency for intercom integration conversations retrieval

- CHANGELOG.md
- package.json
- yarn.lock
> feat(integration): allow user to choose custom mapping values for intercom integration

- CHANGELOG.md
- src/services/resource-updater.js
> fix(update): update records of collections having a "length" field

- .travis.yml
- CHANGELOG.md
- package.json
- yarn.lock
> ci: make the ci lint the commit messages

- CHANGELOG.md
- package.json
- yarn.lock
> chore(forest-express): upgrade forest-express dependency to 7.2.0

- CHANGELOG.md
- src/services/composite-keys-manager.js
- test/index.test.js
- test/services/composite-keys-manager.test.js
- test/services/resources-remover.test.js
The impact of the `GLUE` character change should be minimal. If you have a better char idea for this `GLUE`, I would update it accordingly ;)
Please also see the previous PR (closed) to get more context about the issue and the proposed fix :)
> fix: change the composite key GLUE character

- package.json
- yarn.lock
> fix(dependencies): update babel to fix compilation error introduced by node lts 12.17.0

- package.json
- yarn.lock
> feat(forest-express): upgrade forest-express to 7.3.0 to add the scope validation feature

- package.json
- src/index.js
- yarn.lock
> fix(services): create and expose records remover

- src/services/filters-parser.js
- src/utils/query.js
- test/fixtures/db.json
- test/index.test.js
- test/services/filters-parser.test.js
Task linked: https://app.clickup.com/t/66mm6g
I don't know if we should put this as a breaking change 🤔 ?
> feat(filter): is blank now also filter empty strings

- src/services/search-builder.js
fix extended search with foreign key as string primary key
Fixes: https://app.clickup.com/t/4ajpk5
> fix(search): return expected data on extended search on relations having string primary key

- package.json
- yarn.lock
Fixes a lodash vulnerability imported through forest-express
Clickup card: https://app.clickup.com/t/6up7hd
> fix(vulnerability): patch potential vulnerabilities updating forest-express to version 7.4.1

- .gitignore
> chore: :wrench: ignore .vscode directory

- src/services/has-many-getter.js
Remove useless fields of the parent model from the request
Linked to CU-4rg1z2
I cannot create tests on this modification, because the requested fields were never returned by the function, which is returning `record[params.associationName]`, and never `record[model.name]`.
```sql
SELECT
"user"."id",
"user"."email",
"user"."firstName",
"user"."lastName",
"user"."username",
"user"."password",
"user"."phone",
"user"."createdAt",
"user"."updatedAt",
"user"."resetPasswordToken",
"user"."isSecure",
"user"."browserSessionHash",
"user"."deletedAt",
"user"."guestId",
"messages"."id" AS "messages.id",
"messages"."content" AS "messages.content",
"messages"."createdAt" AS "messages.createdAt",
"messages"."updatedAt" AS "messages.updatedAt",
"messages"."deletedAt" AS "messages.deletedAt", …
```
> perf: :zap: improve performance of queries on HasMany relationships

- package.json
- yarn.lock
> fix(related data): fix related data display regression introduced in v6.3.3

- package.json
- yarn.lock
Improves developers' life by installing jest types, and thus displaying autocomplete suggestion when typing tests.
> chore: add @types/jest in dev dependencies

- package.json
- yarn.lock
> fix: prevent scopes validation crashes for conditions with boolean or number values

- src/services/has-many-getter.js
- src/services/query-builder.js
- src/services/requested-fields-extractor.js
- src/services/resources-getter.js
- src/services/search-builder.js
- test/index.test.js
- test/services/requested-fields-extractor.test.js
Only returns the ids of related models, when querying a given model with relations, instead of returning all fields of all relations.
Fields `sourceKey`or `targetKey` are needed, depending on whether the relation is a `BelongTo` or a `HasOne` (relations have one or the other).
Example of query, in combination with #474 
```sql
SELECT
"user"."id",
"messages"."id" AS "messages.id",
"messages"."content" AS "messages.content",
"messages"."createdAt" AS "messages.createdAt",
"messages"."updatedAt" AS "messages.updatedAt",
"messages"."deletedAt" AS "messages.deletedAt",
"messages"."authorId" AS "messages.authorId",
"messages"."noteId" AS "messages.noteId",
"messages->mention"."id" AS "messages.mention.id",
"messages->mention"."createdAt" AS "messages.mention.createdAt", …
```
> perf: :zap: only return ids of related records, not all fields

- .babelrc
- package.json
- yarn.lock
> chore: ensure that the code is compatible with node 8+

- src/services/has-many-getter.js
- src/services/requested-fields-extractor.js
- src/services/resources-getter.js
- test/index.test.js
- test/services/requested-fields-extractor.test.js
Regression introduced by #477
Should fix #503
Linked to CU-7yqxa0
> fix: :bug: fix retrieved fields from the database when a smart field is used as a reference field

- src/services/search-builder.js
- test/fixtures/db.json
- test/index.test.js
> fix: allow search on fields number

- src/services/leaderboard-stat-getter.js
The query was badly generated by sequelize because we were trying to actually "hack" how sequelize work. Instead of doing that I just generated the query manually
> fix(leaderboard chart): fix query on many to many relationship

- src/services/query-builder.js
- test/services/query-builder.test.js
> fix: fix an error when accessing tables with a hasOne relationship

- .eslint-bin/pre-commit-hook.js
Partial copy of this contribution:
https://github.com/ForestAdmin/forest-express/pull/462/files
> chore:  fix pre-commit hook for file deletion and renames

- .travis.yml
The problem with node 14 can be reproduced locally, I'll try to handle it in another PR
> chore: use nodejs 12 for tests

- src/services/query-builder.js
- test/services/query-builder.test.js
> fix: request the right fields for belongsTo relationships with casing difference between DB and JS

- jest.config.js
> test(coverage): computed the coverage based on source code only

- .eslintrc.js
- .travis.yml
- test/adapters/sequelize.test.js
- test/databases.js
- test/index.test.js
- test/services/apimap-field-builder.test.js
> test: fix existing openHandles issues

- .travis.yml
> chore: use the LTS version of node for tests

- package.json
- yarn.lock
> fix: don't compute smart fields when not requested on associated records

- package.json
- yarn.lock
See: https://github.com/ForestAdmin/forest-express/pull/535
> feat(smart actions): add hooks in schema file

- package.json
> chore: improve build watch command to build cascade forest-express

- .travis.yml
> chore(ci): enable beta distribution channel for semantic-release

- package.json
- yarn.lock
> chore(security): patch semantic release vulnerability

- yarn.lock
> chore(security): patch node-fetch vulnerability

- src/index.js
- test/index.test.js
> fix: export error handler middleware

- package.json
- yarn.lock
> chore(forest-express): upgrade forest-express dependency to 7.7.2

- package.json
- yarn.lock
> chore: update forest-express version

- src/services/leaderboard-stat-getter.js
- test/services/leaderboard-stat-getter.test.js
> fix(leaderboard): fix an error when use "user" table

- package.json
- yarn.lock
> feat(smart actions): introduce smart action forms hooks

- package.json
- yarn.lock
> fix: array display with smart field

- package.json
- yarn.lock
> fix: fix related data list display

- package.json
- yarn.lock
> fix: display correct reference field when it is a smartfield

- package.json
- yarn.lock
> chore(force-release): upgrade dependency forest-express

- src/services/filters-parser.js
> style(force-release): fix typos

- package.json
- yarn.lock
> fix: connect to liana through safari

- package.json
- yarn.lock
> fix: user being disconnected after 33min instead of 14 days

- package.json
- yarn.lock
> fix(authentication): error when authenticating with an invalid token in cookies

- jest.config.js
- package.json
- src/services/filters-parser.js
- test/services/filters-parser.test.js
- yarn.lock
- This require: https://github.com/ForestAdmin/forestadmin/pull/2803
> feat(filter): add possibility to filter on smart field

- package.json
- yarn.lock
> fix(forestadmin-schema): regenerate forestadmin schema only when files are valid

- src/services/belongs-to-updater.js
- src/utils/association-record.js
- test/databases.test.js
> refactor: refactor belongsToUpdater to class

- .eslintrc.js
- src/services/resource-creator.js
> refactor: refactor resourceCreator to class

- .travis.yml
> ci: add docker-hub login step in CI

- package.json
- yarn.lock
> fix(smart-action-hook): value injected to an enum field of type  is now correctly handled

- src/services/belongs-to-updater.js
- src/services/resource-creator.js
- test/databases.test.js
> fix: handle foreign key toward non primary key

- src/services/resource-creator.js
> fix: fix belongsTo relationships creation when creating a record

- .releaserc.js
- package.json
- yarn.lock
> chore: fix the release of new versions

- src/services/belongs-to-updater.js
- test/databases.test.js
> fix: correctly set fields holding  belongsTo relationships to null when updated with a null value

- src/services/resource-creator.js
> fix: fix unconventional pk when referenced as null on creation

- package.json
- yarn.lock
> feat: return correct errors when the users needs to configure the 2FA

- commitlint.config.js
> ci: consider all linting errors about line length as warnings

- commitlint.config.js
> ci: consider commit linting errors about length as warnings

- package.json
- yarn.lock
> chore: bump forest-express version to 8.0.0-beta.13

- .github/workflows/build.yml
- README.md
> refactor(ci): simplify CI configuration

- .eslintrc.js
- src/services/search-builder.js
- test/databases.test.js
- test/fixtures/db.json
> fix(search): handle large numbers in search queries

- .github/workflows/build.yml
- CHANGELOG.md
- README.md
- src/adapters/sequelize.js
- src/services/resource-creator.js
- src/services/search-builder.js
- src/utils/primaryKey-is-ForeignKey.js
- test/adapters/sequelize.test.js
- test/databases.test.js
- test/fixtures/db.json
> chore: merge master

- package.json
- yarn.lock
> chore: use the latest released version of forest-express

- src/adapters/sequelize.js
> chore: merge master into beta

- package.json
- yarn.lock
> fix(authentication): safari cannot login on remote lianas because of third party cookies

- package.json
- yarn.lock
> fix(security): patch lodash vulnerabilities

- .babelrc
- package.json
- src/services/composite-keys-manager.js
- src/services/filters-parser.js
- src/services/has-many-dissociator.js
- src/services/resources-getter.js
- src/services/search-builder.js
- src/services/value-stat-getter.js
- src/utils/operators.js
- test/services/filters-parser.test.js
- test/utils/operators.test.js
- yarn.lock
> feat(filter): add "includes all" filter to array type

- package.json
- yarn.lock
> fix(authentication): unable to login when the agents respond to an url starting with a prefix

- package.json
- yarn.lock
> fix(security): decrease the time before expiration of forest session token

- package.json
- yarn.lock
> feat(security): authorised only allowed stats queries using permissions

- package.json
- yarn.lock
> fix(security): downgrade forest-express while the charts are broken

- package.json
- yarn.lock
> fix(security): authorised only allowed stats queries using permissions

- src/services/apimap-field-type-detector.js
> feat(browsing-context): allow `Forest-Context-Url` header to give the current browser url of users

- package.json
- yarn.lock
> fix(security): patch forest-express transitive vulnerabilities

- src/services/resources-getter.js
- test/databases.test.js
- test/fixtures/db.json
> refactor: migrate ResourcesGetter to class

- package.json
- yarn.lock
> chore(force-release): update forest-express to v8.1.4

- package.json
- yarn.lock
> feat(smart-action): support hooks for smart collection

- package.json
- yarn.lock
> fix(date-filter): filtering only on hours now returns the expected records

- src/index.js
- src/public/parse-filter.js
- test/public/parse-filter.test.js
> feat: expose utils to parse filters

- src/services/search-builder.js
- test/databases.test.js
> fix(search): searching for a big int value should not break if there is a regular integer field

- src/services/search-builder.js
- test/databases.test.js
- test/fixtures/db.json
> fix(search): enable to search for a big integer in an ID field

- src/adapters/sequelize.js
https://github.com/ForestAdmin/forest-express-sequelize/pull/528
> fix(schema): do not remove primary key fields from the schema when tables have foreign keys that are primary keys

- package.json
- yarn.lock
> feat: support yarn 2 plug n play install mode

- src/services/composite-keys-manager.js
- src/services/has-many-getter.js
- src/services/primary-keys-manager.js
- src/services/resource-creator.js
- src/services/resource-finder.js
- src/services/resource-getter.js
- src/services/resource-updater.js
- src/services/resources-getter.js
- src/services/resources-remover.js
- test/services/composite-keys-manager.test.js
- test/services/primary-keys-manager.test.js
- test/services/resources-remover.test.js
This pull request is preparation work for the application wide scopes.
It factorize calls to composite key manager
> refactor: factorize composite key handling

- src/services/has-many-getter.js
- src/services/leaderboard-stat-getter.js
- src/utils/query.js
- test/integration/leaderboard-stat-getter.test.js
> feat(scopes): apply scopes on leaderboard charts

- src/services/resource-remover.js
> refactor: rewrite ResourceRemover as class and factorize code 

- src/services/resource-getter.js
- test/databases.test.js
Note: diff-coverage is at 100%
> refactor: transform ResourceGetter into class and use QueryOptions

- src/services/resources-remover.js
- test/services/resources-remover.test.js
> refactor: use query-options generator on resources-remover

- src/services/value-stat-getter.js
- test/databases.test.js
> refactor: rewrite ValueStatGetter as class and use QueryOptions 

- src/services/pie-stat-getter.js
> refactor: use query-options generator on pie-stat-getter

- src/services/line-stat-getter.js
- test/databases.test.js
> refactor: use query-options generator on line-stat-getter

- package.json
- yarn.lock
> fix: distribution charts using groupby on a relationship throws 403 Forbidden

- package.json
- yarn.lock
> fix(smart-actions-change-hook): record is no longer altered and is sent correctly

- src/services/has-many-getter.js
- src/services/leaderboard-stat-getter.js
- src/services/line-stat-getter.js
- src/services/pie-stat-getter.js
- src/services/resource-creator.js
- src/services/resource-getter.js
- src/services/resource-remover.js
- src/services/resource-updater.js
- src/services/resources-exporter.js
- src/services/resources-getter.js
- src/services/resources-remover.js
- src/services/value-stat-getter.js
- test/databases.test.js
- test/integration/leaderboard-stat-getter.test.js
- test/services/has-many-getter.test.js
- test/services/resources-remover.test.js
> feat: check scopes on services

- src/services/query-options.js
- src/services/search-builder.js
- test/integration/smart-field.test.js
> fix: allow injection of relations when using smartfield' search feature

- package.json
- yarn.lock
> feat(schema): move some meta data under stack attribute to prevent blocking scenarios on DWO

- package.json
- yarn.lock
> fix: correctly get the IP address from the request headers

- package.json
- yarn.lock
> fix:  correctly get the IP address from the request headers

- package.json
- src/services/has-many-getter.js
- src/services/query-options.js
- test/services/query-options.test.js
- test/services/resources-remover.test.js
- yarn.lock
> fix: fix mssql ordering collection by pk

- package.json
- yarn.lock
> feat: include role in the user data inside the request

- package.json
- yarn.lock
> fix: prevent IP check from failing for the proxies including the port in the headers

- test/integration/smart-field.test.js
> test: add smartfield with search test cases

- package.json
- yarn.lock
> fix(intercom): fix date conversion from unix timestamp to js date of intercom attributes

- .github/workflows/build.yml
> chore: fix the version of semantic release

- package.json
- yarn.lock
> fix(authentication): error during authentication when the environment is secret passed as a liana option and not an environment variable

- .github/PULL_REQUEST_TEMPLATE.md
- package.json
- types/.eslintrc.js
- types/index.d.ts
- yarn.lock
The is the first attempt of adding Types definition in our repo directly. 
The `how to translate your app into typescript` page on the Woodshop is, by far, the second most consulted page. 
Some of our top paying clients using mongoose develops using Typescript
We recently have been addressed some issues regarding our Types definition in the community (see this [card](https://app.clickup.com/t/kn5vb3) for more info)
Maintaining Types in DefinitelyTyped has been done using a _community_ approach till now. This leads to some frustration when users upgrade their lianas without updates on their types. Some of our dependencies also have stoped working DefinitelyTyped and integrate their own Types directly in their repos, which makes hard if not impossible to synchronise our own Types. …
> feat: add typescript declaration file

- package.json
- yarn.lock
> feat(security): secure segments queries

- types/.eslintrc.js
> chore: enforce array syntax for types

- types/index.d.ts
> fix: add missing Json value for FieldType Type

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/build.yml
- CHANGELOG.md
- README.md
- package.json
- src/adapters/sequelize.js
- src/services/has-many-getter.js
- src/services/leaderboard-stat-getter.js
- src/services/pie-stat-getter.js
- src/services/query-options.js
- src/services/value-stat-getter.js
- src/utils/orm.js
- src/utils/query.js
- src/utils/sequelize-compatibility.js
- test/services/has-many-getter.test.js
- test/services/query-options.test.js
- test/services/resources-remover.test.js
- test/utils/query.test.js
- test/utils/sequelize-compatibility.test.js
- types/.eslintrc.js
- types/index.d.ts
- yarn.lock
Warning: when merging this, DO NOT squast (use fast-forward)
> chore: merge master into beta + typing

- types/index.d.ts
> fix: add isSearchable to collection options

- package.json
- yarn.lock
> chore: add express type dependency

- package.json
- types/index.d.ts
- yarn.lock
> feat: allow hooks for global and bulk smart action

- package.json
- yarn.lock
> chore(force-release): update forest-express to V9

- src/services/line-stat-getter.js
> fix: fix display of week number in line chart

- package.json
- src/services/resource-updater.js
- yarn.lock
> fix(update): fix update record regression when using scopes

- src/adapters/sequelize.js
> fix: inverseOf computation with multiple associations is supported

- types/index.d.ts
> fix(types): add missing RecordSerializer

- package.json
- types/index.d.ts
- yarn.lock
> fix(exposed): reduce number of mandatory parameters in records-getter and record-serializer

- src/utils/sequelize-compatibility.js
> fix(queries): query generation for camelCased fields on related data

- package.json
- yarn.lock
> fix(charts): objective charts now returns correct values

- package.json
- src/services/has-many-getter.js
- src/services/query-options.js
- src/services/resources-getter.js
- test/databases.test.js
- yarn.lock
> perf: queries should select only the requested fields

- src/services/filters-parser.js
- test/services/filters-parser.test.js
> feat(filter): add "is in" filter

- package.json
- src/services/filters-parser.js
- src/utils/orm.js
- test/databases.test.js
- test/services/filters-parser.test.js
- yarn.lock
https://github.com/ForestAdmin/forest-express/pull/795
> fix(smart field): fix filter on smart reference

- package.json
- yarn.lock
> fix(segments): after fixing performance issue, some segments were ignored by delete and smart actions

- package.json
- yarn.lock
> fix(security): patch semantic-release dependency vulnerabilities

- yarn.lock
> fix(security): patch dependencies of dependencies vulnerabilities

- src/services/query-options.js
- src/services/resources-getter.js
- test/databases.test.js
> fix(resources getter): retrieve only the requested fields if no smart fields are requested

- package.json
- yarn.lock
> fix: smart actions restricted to a segment using segment query should be visible

- src/services/apimap-field-type-detector.js
- test/databases.test.js
- test/services/apimap-field-builder.test.js
https://app.clickup.com/t/1crurfp
https://app.clickup.com/t/1cruua8
https://github.com/ForestAdmin/forestadmin/pull/3675
> feat(filter): handle correctly uuid field type

- types/index.d.ts
Co-authored-by: @felipe-augusto
Due to our CI requiring docker password as an env var, this is just a copy of #844.
> fix(types): update smart action hook return type

- types/index.d.ts
> docs(force-release): add searchFields type in the collection options

- package.json
- yarn.lock
> chore: deprecate old versions without error when releasing a version

- src/services/requested-fields-extractor.js
- test/services/requested-fields-extractor.test.js
> fix: return field data even when the field have the same name as the model

- src/services/belongs-to-updater.js
- src/services/resource-creator.js
- test/services/belongs-to-updater.test.js
- test/services/resource-creator.test.js
> fix: fix association with primary key different of 'id'

- src/services/query-builder.js
- src/services/query-options.js
- src/services/resources-getter.js
> fix(count): remove useless joins in basic count

- types/index.d.ts
> fix(types): serializers now take optional meta as second argument

- package.json
- yarn.lock
> fix: prevent deactivate count middleware to throw

- package.json
- yarn.lock
> chore(force-release): bump forest-express from 9.4.1 t 9.4.2

- package.json
- yarn.lock
> chore(force-release): bump forest-express from 9.4.3 to 9.4.6

- package.json
- yarn.lock
> fix(security): patch express-jwt to latest stable candidate

- package.json
- yarn.lock
> fix(stripe): crash early when stripe integration is misconfigured

- docker-compose.yml
- test/adapters/sequelize.test.js
- test/databases.js
- test/databases.test.js
> chore: add test for mariadb support

- types/index.d.ts
> fix(types): declare correctly user in requests

- types/index.d.ts
> fix(types): load and change hook are now optional on smart action

- package.json
- yarn.lock
> fix(security):  upgrade moment to 2.29.4 to fix a vulnerability

- package.json
- yarn.lock
> fix(charts): user with permissions level that allows charts creation or edition should always be allow to perform charts requests

- .releaserc.js
> chore: correctly release beta version and support versions

- package.json
- test/services/filters-parser.test.js
- yarn.lock
> fix(security): validate that smart action approvals are launched with the same parameters than the initial trigger

- package.json
- yarn.lock
> feat(chart): add support for context variables used by Workspaces

- package.json
- src/services/query-stat-getter.js
- yarn.lock
> feat(chart): add support for context variables inside SQL query

- test/databases.test.js
> test: add tests on QueryStatGetter

- types/index.d.ts
> fix(types): remove unused and incorrect exported type related to aggregation

- types/index.d.ts
As defined on `forest-express` the `filter` function of `smart-fields` can be async [here](https://github.com/ForestAdmin/forest-express/blob/160e439577dc6f3540ddea33273eff8a32bfa399/src/services/base-filters-parser.js#L34)
```
const formattedCondition = await fieldFound
.filter({
where,
condition,
});
```
> fix(type): add promise return for `SmartFieldFilterer`

- types/index.d.ts
Proposal based on [filter-parser](https://github.com/ForestAdmin/forest-express-sequelize/blob/b99f5e77e02acb96a9d46503f5fb907a6ab46d1a/src/services/filters-parser.js#L56) and [filter-date-parser](https://github.com/ForestAdmin/forest-express/blob/main/src/services/base-operator-date-parser.js)
> fix(type): add FilterOperator enum

- package.json
- yarn.lock
> fix: add attribute reverse list word by upgrading forest-express

- package.json
- yarn.lock
> chore: update forest-express dependency to fix qs vulnerability

- types/index.d.ts
> fix(typing): remove invalid enum from typing file

- package.json
- yarn.lock
Reverts ForestAdmin/forest-express-sequelize#1052
> fix: revert "feat(smart-actions): add support for data-based conditions on smart action trigger, approval requirement and authorization to approve"

- package.json
- yarn.lock
> feat(smart-actions): allow to define data-based conditions on approval requests

- yarn.lock
> fix(security): patch xmldom dependency vulnerability

- package.json
- yarn.lock
> fix(security): patch forest-express dependency vulnerability

- package.json
- yarn.lock
> chore(security): patch sequelize dependency vulnerabilities

- package.json
- yarn.lock
> fix: revert forest-express instable dependency

- docker-compose.yml
- package.json
- yarn.lock
> fix(middlewares): users should be able to execute a smart action on a smart collection

- package.json
- yarn.lock
> fix(security): patch sequelize vulnerabilities

- package.json
- yarn.lock
> fix(init-options): liana options should be taken into account correctly

- package.json
- yarn.lock
> feat(events-subscription): allow to instantly refresh permissions when they change

- yarn.lock
> fix(security): patch dottie dependency vulnerabilities

- package.json
- yarn.lock
Due to https://github.com/ForestAdmin/forest-express/issues/1011
> fix(event-source): gracefully close the app on exit by removing server events subscription

- CHANGELOG.md
- package.json
- yarn.lock
> fix(security): patch word-wrap dependency vulnerabilities

- .github/workflows/build.yml
- package.json
- yarn.lock
> fix(security): patch semver dependency vulnerabilities

- package.json
- yarn.lock
> fix: warn in the console when NODE_ENV prevents from updating the schema

- package.json
- test/databases.js
- yarn.lock
> fix: warn in console when the schema is not updated because of NODE_ENV

- package.json
- yarn.lock
https://stackoverflow.com/questions/48391913/eslint-error-cannot-read-property-range-of-null
> chore(lint): patch linter internal error

- .eslintrc.js
- package.json
- yarn.lock
> fix(security): patch @babel/traverse dependency vulnerabilities

- package.json
- yarn.lock
> fix(serialiser):​ serialiser does not compute hidden smart fields anymore

- package.json
- yarn.lock
> fix: user receives 403 on newly created segment query

- package.json
- yarn.lock
> fix(security): patch ip dependency vulnerabilities

- .github/workflows/build.yml
- package.json
- yarn.lock
> fix: bump tedious dependency to fix vulnerability

- package.json
- yarn.lock
> fix: typo in an error message when users are not authorized to perform an action

- package.json
- yarn.lock
> fix: typo in error message

- package.json
- yarn.lock
> fix(security): patch mysql2 dependency vulnerabilities

- package.json
- yarn.lock
> perf: improve memory usage when exporting

- package.json
- yarn.lock
> feat: support action form layout description and button labels

- types/index.d.ts
Fixes: [1125](https://github.com/ForestAdmin/forest-express-sequelize/issues/1125)
> fix(actions): add missing fields to actions options interface

- .github/workflows/build.yml
- package.json
- yarn.lock
> fix: upgrade FE to fix user perm cache issue

- .github/workflows/build.yml
- src/services/line-stat-getter.js
> fix(charts): handle last week of the year properly during format

- types/index.d.ts
> feat(typings): add support for action_intent_params in smart action hooks
