ForestAdmin/forest-express-sequelize

CHANGELOG.md
services/resource-finder.js

[*] Resource Finder - Fix the record retrieval for a record having no belongsTo/hasOne for projects using Sequelize 4.8.x

---

CHANGELOG.md
services/search-builder.js
test/fixtures/db.json
test/index.js

Fix: https://github.com/ForestAdmin/forest-express-sequelize/issues/141

[*] Search - An extended search on a belongsTo associated model with an UUID value will not crash anymore

---

CHANGELOG.md
services/resource-getter.js

Fix: https://github.com/ForestAdmin/forest-express-sequelize/issues/139

[*] Smart Fields - Always pass a Sequelize instance as the first parameter of the Smart Field value getter functions

---

CHANGELOG.md
src/index.js
src/services/composite-keys-manager.js
src/services/errors.js
src/services/resources-remover.js
test/services/composite-keys-manager.test.js
test/services/resources-remover.test.js

Deleting multiple records 1 by 1 seems instable (it fails with 5000 records for @jeffladiray) and is slow. This PR adds a new `RecordsRemover` that handles bulk destroy.
Required by: https://github.com/ForestAdmin/forest-express/pull/346

[+] Resources Remover - Add resources remover (bulk destroy)

---

CHANGELOG.md
src/services/query-builder.js

Remove this warning by using the [return early pattern](http://www.itamarweiss.com/personal/2018/02/28/return-early-pattern.html): 
> 46:44  warning  Refactor this function to reduce its Cognitive Complexity from 17 to the 15 allowed  sonarjs/cognitive-complexity
(hide whitespace, there are only a few changes)

[*] Technical - Remove cognitive complexity in query-builder service

---

test/services/filters-parser.test.js

This expectation is not at the right place in the tests, it is not in a test but in a `describe` section, and it fails when launching jest on a given test (when developing).
The only test in the section already has the same declaration, that's why I just removed this line.

test: remove useless assertion that is not in a test

---

.babelrc
package.json
yarn.lock

Arrow functions were no longer transformed to normal function after specifying the build target. As exported function are used with the new keyword in some context (even if they should not), this caused a crash when launching an agent.
Linked to CU-7rv8fc
There is a mismatch between what is exported by `forest-express-sequelize` and what is expected by `forest-express`:
- `forest-express-sequelize` exports a plain function
- `forest-express` uses it as a constructor
Which one is right in this case?

fix: :bug: fix a regression introduced by changes in the build

---

package.json
yarn.lock

Related to #532
Running tests on node 14 fails because the package `pg` does not seem to be compatible with this version.

chore: upgrade pg to support running tests on node 14

---

src/services/query-builder.js
test/services/query-builder.test.js

- ✅ &nbsp; Tested with the model that shown the error in Forest Admin
- ✅ &nbsp; Tested with the model from https://app.clickup.com/t/8ppqbf

fix: always return primary keys of associated records

---

src/services/leaderboard-stat-getter.js
src/services/line-stat-getter.js
src/services/pie-stat-getter.js
src/services/resources-getter.js
src/services/search-builder.js
src/utils/database.js
test/adapters/sequelize.test.js
test/databases.js
test/index.test.js

fix: fix incorrect usage of the new connections parameter

---

.releaserc.js
package.json
yarn.lock

Reverts ForestAdmin/forest-express-sequelize#592

chore: revert "chore: mark versions older than the latest major - 3 as deprecated on npm"

---

src/adapters/sequelize.js
src/services/resource-creator.js
src/utils/primaryKey-is-ForeignKey.js
test/adapters/sequelize.test.js
test/databases.test.js
yarn.lock

- [forest-express](https://github.com/ForestAdmin/forest-express/pull/616)
- [forest-admin](https://github.com/ForestAdmin/forestadmin/pull/2898)
- [forest-admin-server](https://github.com/ForestAdmin/forestadmin-server/pull/2009)
Please follow in the right order theses steps, as there is still an issue with the forestadmin-server update
1. Switch to the `fix-primary-foreign-key-to-primary-key` on every projects
2. Launch forestadmin-server and forestadmin
3. In the forest-express project, run `yarn build:watch`
4. In the forest-express-sequelize, run `yarn link forest-express`, then `yarn build:watch`
5. Create a postgresql database with this dump:
```
create table if not exists customer
(
id serial not null
constraint customer_pk
primary key,
name varchar not null
);
create unique index …
```

fix: fix record creation with unconventional pk field acting as a fk

---

package.json
yarn.lock

fix: support foreign and primary key column

---

src/adapters/sequelize.js

fix: fix error when no foreign key is found but foreign and primary key

---

src/services/has-many-getter.js
src/services/query-builder.js
test/services/has-many-getter.test.js
test/services/query-builder.test.js

diff-coverage is 100%
global coverage goes down because we're factorizing covered code.

refactor: rewrite has-many-getter as a subclass of resources-getter

---

src/services/has-many-getter.js
src/services/line-stat-getter.js
src/services/pie-stat-getter.js
test/databases.test.js

Fix:
https://community.forestadmin.com/t/unexpected-error-cannot-read-property-map-of-undefined-after-update-to-v7-8-0/2479/9
The bug was that when crafting sequelize queries, `include: undefined` is NOT equivalent to not setting the field.
@see https://github.com/sequelize/sequelize/blob/v5.15.1/lib/model.js#L704-L706

fix: regression when fetching has-many and not selecting any fields on a hasone/belongsto relation

---

package.json
src/services/has-many-getter.js
src/services/leaderboard-stat-getter.js
src/services/line-stat-getter.js
src/services/pie-stat-getter.js
src/services/resource-creator.js
src/services/resource-getter.js
src/services/resource-remover.js
src/services/resource-updater.js
src/services/resources-exporter.js
src/services/resources-getter.js
src/services/resources-remover.js
src/services/value-stat-getter.js
test/databases.test.js
test/integration/leaderboard-stat-getter.test.js
test/services/has-many-getter.test.js
test/services/resources-remover.test.js
yarn.lock

feat(scopes): enforce scopes restrictions on a wider range of requests

---

package.json
yarn.lock

BREAKING CHANGE: fields parameters on hook function is no longer a map of field, it is now an array.
change hook is no longer choosen by the field name, field need to have hook defined inside it definition by addin a props hook.

feat(smart-action): user can add dynamically field with hook on smart action form

---

src/services/has-many-getter.js
src/services/pie-stat-getter.js
src/services/query-options.js
src/services/value-stat-getter.js
src/utils/orm.js
src/utils/query.js
src/utils/sequelize-compatibility.js
test/services/has-many-getter.test.js
test/utils/query.test.js
test/utils/sequelize-compatibility.test.js

Fix retrocompatibility with sequelize 4.
The issue in the ticket is due to the fact than in Sequelize 4, it is illegal to join the same relation twice.
This happens in smart field cutom search, when customers inject "include" into the query options
```
{
// illegal in sequelize@4, OK in sequelize@5 and 6
include: [
{ as: 'something', model: Something },
{ as: 'something', model: Something }
]
```

fix(retrocompatibility): make test suite pass with sequelize@4.x

---

src/adapters/sequelize.js

fix: correctly support inverseOf between relationships

---

types/index.d.ts

fix: abstractRecord type

---

src/services/query-options.js

The class was written so that methods can be called in any order without changing the generated query.
This may cause problems in the future

refactor(query generation): avoid getter side effects on QueryOptions

---

types/index.d.ts

fix(types): fix typing errors and limitations

---

docker-compose.yml
test/databases.js
test/services/apimap-field-builder.test.js

Changing the Postgres testing port to allow developers test the project with his development environment (eg: `forest_postgres_renderings` turn on 5436)

chore: change postgres testing port to allow testing in local environment

---

types/index.d.ts

According to doc: https://docs.forestadmin.com/documentation/reference-guide/smart-fields/smart-field-examples/sort-by-smart-field, smart field option should allow to set property `isSortable` as optional boolean

fix(type): add "isSortable" to SmartFieldOptions interface

---

package.json
yarn.lock

…
Linked to CU-35d7gv6, CU-35d7h2b, CU-35d7h4d

feat(smart-actions): add support for data-based conditions on smart action trigger, approval requirement and authorization to approve

---

src/services/resource-creator.js
src/services/resource-updater.js
test/services/resource-creator.test.js
test/services/resources-updater.test.js

fix: create and update with a scope when it is not found

---

docker-compose.yml
yarn.lock

fix(security): patch ws dependency vulnerabilities

---

.github/workflows/build.yml
docker-compose.yml
yarn.lock

fix(security): patch micromatch dependency vulnerabilities
